export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",

  SET_BASKET: "SET_BASKET",
  SET_BASKET_LOADING: "SET_BASKET_LOADING",
  SET_BASKET_ERROR: "SET_BASKET_ERROR",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  UPDATE_ITEM: "UPDATE_ITEM",
};
